### ISSUE TITLE
Description + Exclude

### ISSUE THREAD

**Issue by egor-xyz** [ruyadorno/ntl#41] opened 2019-03-18 16:16 UTC
`ntl -d -e start`
Didn't exlude start script from menu

**Comment by mischah** [comment] 2019-03-18 22:40
Confirmed. I’m able to reproduce this with ntl `v3.2.3`.

Seems to be a bug. 

@ruyadorno Can you assign this one to me?

**Comment by ruyadorno** [comment] 2019-03-19 17:07
sure thing 👍

**Closed** 2019-03-19 17:10 UTC

**Comment by ruyadorno** [comment] 2019-03-19 17:14
thanks for the prompt fix @mischah 😄

**Comment by ruyadorno** [comment] 2019-03-19 17:15
and @egor-xyz for the prompt report! 🎉
