### ISSUE TITLE
Task description

### ISSUE THREAD

**Issue by rafaelrinaldi** [ruyadorno/ntl#17] opened 2018-03-23 23:58 UTC
It would be very handy if `ntl` provided a way to display a description about the available tasks. I believe it would be failry straightforward to implement this.

If you think it's a good idea I can give it a shot.

**Comment by ruyadorno** [comment] 2018-03-24 03:26
hey @rafaelrinaldi thanks for stopping by!

by task descriptions do you mean like we discussed in #4 ?

**Comment by rafaelrinaldi** [comment] 2018-03-24 03:47
That looks like it! I offer myself to tackle it if there is interest.

**Comment by ruyadorno** [comment] 2018-03-24 04:25
oh yeah 🎉 sure thing! that'd be awesome!

in the end of that discussion I think the [bash comment](https://github.com/npm/npm/issues/15154#issuecomment-275791993) idea was the best way to go about it we could come up with, do you agree?

anyways, any help is super appreciated!

many thanks!

**Comment by ruyadorno** [comment] 2018-04-03 14:48
@rafaelrinaldi heads up, major refactor just landed on master 😊

**Comment by ruyadorno** [comment] 2018-04-05 01:59
I'll close this one since it's def a duplicate of #4 

let's follow up with the discussion there! many thanks!

**Closed by ruyadorno** 2018-04-05 01:59 UTC
